module.exports = {
    userinfo: require('./users/UserInfo'),
    auth: require('./users/Auth'),
    register: require('./users/Register'),
    unRegister: require('./users/UnRegister'),
    login: require('./users/LogIn'),
    logout: require('./users/LogOut'),
    kakaogooglelogin: require('./users/KakaoGoogleLogIn'),
    images: require('./healings/Image'),
    sounds: require('./healings/Sound'),
    posts: require('./boards/BoardList'),
    post: require('./boards/Board'),
    comments: require('./boards/CommentList'),
    addComment: require('./boards/CommentAdd'),
    DeleteComment: require('./boards/CommentDelete'),
    AddPost: require('./boards/BoardAddUpdate'),
    DeletePost: require('./boards/BoardDelete'),
};